

CREATE TABLE USERS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NAME NVARCHAR(100) NOT NULL,
    PASSWORD NVARCHAR(100) NOT NULL,
    ROLEID INT NOT NULL,
    FOREIGN KEY (ROLEID) REFERENCES ROLES(ROLEID)
);

ALTER TABLE USERS ADD PHOTO VARBINARY(MAX) NULL;